// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	service "url-shortener/internal/service"
)

// URLSaver is an autogenerated mock type for the URLSaver type
type URLSaver struct {
	mock.Mock
}

// RegisterSaveURL provides a mock function with given fields: inputReq
func (_m *URLSaver) RegisterSaveURL(inputReq service.CreateURLInput) (string, error) {
	ret := _m.Called(inputReq)

	if len(ret) == 0 {
		panic("no return value specified for RegisterSaveURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(service.CreateURLInput) (string, error)); ok {
		return rf(inputReq)
	}
	if rf, ok := ret.Get(0).(func(service.CreateURLInput) string); ok {
		r0 = rf(inputReq)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(service.CreateURLInput) error); ok {
		r1 = rf(inputReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewURLSaver creates a new instance of URLSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLSaver {
	mock := &URLSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
