// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	service "url-shortener/internal/service"

	mock "github.com/stretchr/testify/mock"
)

// URLUpdater is an autogenerated mock type for the URLUpdater type
type URLUpdater struct {
	mock.Mock
}

// RegisterUpdateURL provides a mock function with given fields: inputReq
func (_m *URLUpdater) RegisterUpdateURL(inputReq service.UpdateURLInput) (int64, error) {
	ret := _m.Called(inputReq)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUpdateURL")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(service.UpdateURLInput) (int64, error)); ok {
		return rf(inputReq)
	}
	if rf, ok := ret.Get(0).(func(service.UpdateURLInput) int64); ok {
		r0 = rf(inputReq)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(service.UpdateURLInput) error); ok {
		r1 = rf(inputReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewURLUpdater creates a new instance of URLUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLUpdater {
	mock := &URLUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
